services:
  cockroach:
    image: cockroachdb/cockroach:v25.3.3
    container_name: cockroach
    restart: unless-stopped
    command: start-single-node --insecure --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8080
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - ${COCKROACH_DATA_DIR:-/opt/dockyard/cockroach}:/cockroach/cockroach-data
    networks:
      - dockyard_foundation

networks:
  dockyard_foundation:
    external: true
